spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuan724590/config
#          username:
#          password:
          search-paths: configs/
          default-label: main
          timeout: 50
#          basedir: target/config
  application:
    name: yuan-springcloud-config
server:
  port: 40000